### ISSUE TITLE
Plugin installation fails for Kibana 7.10.2

### ISSUE THREAD

**Issue by cinhtau** [lizozom/custom-kibana-theme#10]
I created the zip file for Version 7.10.2

Installed into a fresh vanilla Kibana installation

```bash
tan@omega:~/test/elastic/kibana-7.10.2-linux-x86_64$ bin/kibana
  log   [08:32:02.770] [error][plugins-service] { Error: Manifest for plugin "customKibanaTheme" contains the following unrecognized properties: owner,description,enabledOnAnonymousPages. (invalid-manifest, /home/tan/test/elastic/kibana-7.10.2-linux-x86_64/plugins/customKibanaTheme/kibana.json)
    at Function.invalidManifest (/home/tan/test/elastic/kibana-7.10.2-linux-x86_64/src/core/server/plugins/discovery/plugin_discovery_error.js:55:12)
    at parseManifest (/home/tan/test/elastic/kibana-7.10.2-linux-x86_64/src/core/server/plugins/discovery/plugin_manifest_parser.js:151:56)
  type: 'invalid-manifest',
  path:
   '/home/tan/test/elastic/kibana-7.10.2-linux-x86_64/plugins/customKibanaTheme/kibana.json',
  cause:
   Error: Manifest for plugin "customKibanaTheme" contains the following unrecognized properties: owner,description,enabledOnAnonymousPages.
       at parseManifest (/home/tan/test/elastic/kibana-7.10.2-linux-x86_64/src/core/server/plugins/discovery/plugin_manifest_parser.js:151:86) }
  log   [08:32:02.785] [fatal][root] Error: Failed to initialize plugins:
	Manifest for plugin "customKibanaTheme" contains the following unrecognized properties: owner,description,enabledOnAnonymousPages. (invalid-manifest, /home/tan/test/elastic/kibana-7.10.2-linux-x86_64/plugins/customKibanaTheme/kibana.json)
    at PluginsService.handleDiscoveryErrors (/home/tan/test/elastic/kibana-7.10.2-linux-x86_64/src/core/server/plugins/plugins_service.js:122:13)

 FATAL  Error: Failed to initialize plugins:
	Manifest for plugin "customKibanaTheme" contains the following unrecognized properties: owner,description,enabledOnAnonymousPages. (invalid-manifest, /home/tan/test/elastic/kibana-7.10.2-linux-x86_64/plugins/customKibanaTheme/kibana.json)
```

**Comment by cinhtau** [comment]
Remove the properties from `kibana.json` and it starts normal.
Seems that these new properties have been introduced afterwards.
I guess nothing can be done in generating those.

**Comment by cinhtau** [comment]
When accessing Kibana I receive `__kbnSharedDeps_npm__ is not defined`

```
Version: 7.10.2
Build: 36136
Error: __kbnSharedDeps_npm__ is not defined
@http://localhost:5601/36136/bundles/plugin/customKibanaTheme/customKibanaTheme.plugin.js:1:19775
n@http://localhost:5601/36136/bundles/plugin/customKibanaTheme/customKibanaTheme.plugin.js:1:110
@http://localhost:5601/36136/bundles/plugin/customKibanaTheme/customKibanaTheme.plugin.js:1:9902
n@http://localhost:5601/36136/bundles/plugin/customKibanaTheme/customKibanaTheme.plugin.js:1:110
@http://localhost:5601/36136/bundles/plugin/customKibanaTheme/customKibanaTheme.plugin.js:1:19931
n@http://localhost:5601/36136/bundles/plugin/customKibanaTheme/customKibanaTheme.plugin.js:1:110
get@http://localhost:5601/bootstrap.js:28:25
read@http://localhost:5601/36136/bundles/core/core.entry.js:13:309228
_callee3$@http://localhost:5601/36136/bundles/core/core.entry.js:13:313741
l@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982071
s/o._invoke</<@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:981825
_/</e[t]@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982428
plugin_asyncGeneratorStep@http://localhost:5601/36136/bundles/core/core.entry.js:13:309548
_next@http://localhost:5601/36136/bundles/core/core.entry.js:13:309890
plugin_asyncToGenerator/</<@http://localhost:5601/36136/bundles/core/core.entry.js:13:310034
plugin_asyncToGenerator/<@http://localhost:5601/36136/bundles/core/core.entry.js:13:309777
createPluginInstance@http://localhost:5601/36136/bundles/core/core.entry.js:13:314307
_callee$@http://localhost:5601/36136/bundles/core/core.entry.js:13:312112
l@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982071
s/o._invoke</<@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:981825
_/</e[t]@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982428
plugin_asyncGeneratorStep@http://localhost:5601/36136/bundles/core/core.entry.js:13:309548
_next@http://localhost:5601/36136/bundles/core/core.entry.js:13:309890
plugin_asyncToGenerator/</<@http://localhost:5601/36136/bundles/core/core.entry.js:13:310034
plugin_asyncToGenerator/<@http://localhost:5601/36136/bundles/core/core.entry.js:13:309777
setup@http://localhost:5601/36136/bundles/core/core.entry.js:13:312388
_callee$@http://localhost:5601/36136/bundles/core/core.entry.js:13:323024
l@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982071
s/o._invoke</<@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:981825
_/</e[t]@http://localhost:5601/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982428
plugins_service_asyncGeneratorStep@http://localhost:5601/36136/bundles/core/core.entry.js:13:317120
_next@http://localhost:5601/36136/bundles/core/core.entry.js:13:317480
```

Any idea how I get it running or is v7.10.2 not in the scope of this plugin?

**Comment by lizozom** [comment]
I haven't tested this on older versions, only  7.17.
But I will test this and let you know

**Comment by cinhtau** [comment]
Used newer versions and other products
